// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-pUtWq3NApzhtnC4rdZSrBANqXv5NwF4',
    appId: '1:768693070991:android:62b9af3fae938a86a314fa',
    messagingSenderId: '768693070991',
    projectId: 'saheli-43a79',
    databaseURL: 'https://saheli-43a79-default-rtdb.firebaseio.com',
    storageBucket: 'saheli-43a79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-289nDyrNOe8sZUXOkJvwdgaTs78iSTg',
    appId: '1:768693070991:ios:ed9c46a278616e81a314fa',
    messagingSenderId: '768693070991',
    projectId: 'saheli-43a79',
    databaseURL: 'https://saheli-43a79-default-rtdb.firebaseio.com',
    storageBucket: 'saheli-43a79.appspot.com',
    androidClientId: '768693070991-0mibbl0vgs1470qjlrhe2d5ic8nh9o4t.apps.googleusercontent.com',
    iosClientId: '768693070991-mnp06nkkmk6tc1770a81qspjsddtg4fp.apps.googleusercontent.com',
    iosBundleId: 'com.mighty.taxidriver2',
  );

}